use QLBongDa
go

----PHAN 1----

--1--
select MACT, HOTEN, NGAYSINH, DIACHI, VITRI
from CAUTHU inner join QUOCGIA on CAUTHU.MAQG = QUOCGIA.MAQG inner join CAULACBO on CAUTHU.MACLB = CAULACBO.MACLB
where TENCLB like N'SHB Đà Nẵng' and TENQG like N'Bra-xin'

--2--
select HOTEN
from CAUTHU inner join THAMGIA on CAUTHU.MACT = THAMGIA.MACT
where SOTRAI >= 2

--3--
select MATRAN, NGAYTD, TENSAN, CLB1.TENCLB as TENCLB1, CLB2.TENCLB as TENCLB2, KETQUA
from TRANDAU inner join SANVD on TRANDAU.MASAN = SANVD.MASAN
			 inner join CAULACBO CLB1 on TRANDAU.MACLB1 = CLB1.MACLB
			 inner join CAULACBO CLB2 on TRANDAU.MACLB2 = CLB2.MACLB
where VONG = 3 and NAM = 2009

--4--
select HUANLUYENVIEN.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
from HUANLUYENVIEN inner join HLV_CLB on HUANLUYENVIEN.MAHLV = HLV_CLB.MAHLV
				   inner join CAULACBO on HLV_CLB.MACLB = CAULACBO.MACLB
				   inner join QUOCGIA on HUANLUYENVIEN.MAQG = QUOCGIA.MAQG
where TENQG like N'Việt Nam'